cp "nv_files/rankReviewsNGramsFileN" "$1/rankReviewsNGramsFileN"
cp "nv_files/rankReviewsNGrams" "$1/rankReviewsNGrams"
cp "nv_files/rankReviewsNGramsFull" "$1/rankReviewsNGramsFull"
cp "aux_files/grepResults.txt" "$1/grepResults.txt"
cp "results/reviewCollection.txt" "$1/reviewCollection.txt"
cp "results/phraseDictionary" "$1/phraseDictionary"
